// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	AddUserBalance(ctx context.Context, arg AddUserBalanceParams) (User, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetStockQuantityForUser(ctx context.Context, arg GetStockQuantityForUserParams) (GetStockQuantityForUserRow, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListStockQuantitiesForUser(ctx context.Context, username string) ([]ListStockQuantitiesForUserRow, error)
	ListTransactionsForUser(ctx context.Context, dollar_1 interface{}) ([]Transaction, error)
	ListTransactionsForUserForTicker(ctx context.Context, arg ListTransactionsForUserForTickerParams) ([]Transaction, error)
	RemoveUserBalance(ctx context.Context, arg RemoveUserBalanceParams) (User, error)
}

var _ Querier = (*Queries)(nil)
