// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: transactions.sql

package db

import (
	"context"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
  username,
  ticker,
  quantity,
  price
) VALUES (
  $1, $2, $3, $4
) RETURNING id, username, ticker, quantity, price, created_at
`

type CreateTransactionParams struct {
	Username string  `json:"username"`
	Ticker   string  `json:"ticker"`
	Quantity int64   `json:"quantity"`
	Price    float64 `json:"price"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.Username,
		arg.Ticker,
		arg.Quantity,
		arg.Price,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Ticker,
		&i.Quantity,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}

const getPurchasePriceForTicker = `-- name: GetPurchasePriceForTicker :one
SELECT SUM(price * quantity)::float as purchase_price FROM transactions
WHERE 
    username = $1 AND
    ticker = $2
`

type GetPurchasePriceForTickerParams struct {
	Username string `json:"username"`
	Ticker   string `json:"ticker"`
}

func (q *Queries) GetPurchasePriceForTicker(ctx context.Context, arg GetPurchasePriceForTickerParams) (float64, error) {
	row := q.db.QueryRowContext(ctx, getPurchasePriceForTicker, arg.Username, arg.Ticker)
	var purchase_price float64
	err := row.Scan(&purchase_price)
	return purchase_price, err
}

const getStockQuantityForUser = `-- name: GetStockQuantityForUser :one
SELECT username, ticker, SUM(quantity) as total_quantity FROM transactions
WHERE username = $1 AND ticker = $2 GROUP BY username, ticker LIMIT 1
`

type GetStockQuantityForUserParams struct {
	Username string `json:"username"`
	Ticker   string `json:"ticker"`
}

type GetStockQuantityForUserRow struct {
	Username      string `json:"username"`
	Ticker        string `json:"ticker"`
	TotalQuantity int64  `json:"total_quantity"`
}

func (q *Queries) GetStockQuantityForUser(ctx context.Context, arg GetStockQuantityForUserParams) (GetStockQuantityForUserRow, error) {
	row := q.db.QueryRowContext(ctx, getStockQuantityForUser, arg.Username, arg.Ticker)
	var i GetStockQuantityForUserRow
	err := row.Scan(&i.Username, &i.Ticker, &i.TotalQuantity)
	return i, err
}

const listStockQuantitiesForUser = `-- name: ListStockQuantitiesForUser :many
SELECT ticker, SUM(quantity) as quantity FROM transactions
WHERE username = $1
GROUP BY username, ticker
ORDER BY ticker
`

type ListStockQuantitiesForUserRow struct {
	Ticker   string `json:"ticker"`
	Quantity int64  `json:"quantity"`
}

func (q *Queries) ListStockQuantitiesForUser(ctx context.Context, username string) ([]ListStockQuantitiesForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listStockQuantitiesForUser, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStockQuantitiesForUserRow{}
	for rows.Next() {
		var i ListStockQuantitiesForUserRow
		if err := rows.Scan(&i.Ticker, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsForUser = `-- name: ListTransactionsForUser :many
SELECT id, username, ticker, quantity, price, created_at FROM transactions
WHERE 
    username = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListTransactionsForUserParams struct {
	Username string `json:"username"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListTransactionsForUser(ctx context.Context, arg ListTransactionsForUserParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsForUser, arg.Username, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Ticker,
			&i.Quantity,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsForUserForTicker = `-- name: ListTransactionsForUserForTicker :many
SELECT id, username, ticker, quantity, price, created_at FROM transactions
WHERE 
    username = $1 AND
    ticker = $2
ORDER BY created_at DESC
LIMIT $3
OFFSET $4
`

type ListTransactionsForUserForTickerParams struct {
	Username string `json:"username"`
	Ticker   string `json:"ticker"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListTransactionsForUserForTicker(ctx context.Context, arg ListTransactionsForUserForTickerParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsForUserForTicker,
		arg.Username,
		arg.Ticker,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Ticker,
			&i.Quantity,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
